### ISSUE TITLE
Support for running Haskell in migrations

### ISSUE THREAD

**Issue by gronnbeck** [ameingast/postgresql-simple-migration#32]
First, let me thank you for this library. It looks good and solves most of my issues regarding sql migrations with postgres. Again thank you for sharing this code with the ecosystem. 

In the readme you state that `postgresql-simple-migration` can run Haskell scripts. I'm fairly new to Haskell but reading the documentation it seems that I can only run SQL scripts. Is that right or is it something I have missed? I want to be able to run haskell code to verify certain migrations went as expected and not only execute SQL scripts.

**Comment by ameingast** [comment]
You can only run SQL migrations. They can either be file based or string-based embedded in your Haskell code.

**Comment by gronnbeck** [comment]
Ah ok. Thanks for answering
